name: golangci-lint

on:
  push:
    branches:
  pull_request:
    branches: [ master ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install protobuf compiler
        run: sudo apt-get install protobuf-compiler
      - name: Install protobuf and grpc generators
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generate protobuf and grpc bindings
        run: go generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
